#! /usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
# my $event = "letsencrypt-update";

# letsencrypt-update

foreach (qw(
       /etc/letsencrypt.sh/domains.txt
       /etc/letsencrypt.sh/config.sh
    ))
{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    domain-create
    domain-delete
    domain-modify
    host-create
    host-delete
    host-modify 
    ));
}

foreach (qw(
    /etc/cron.daily/letsencrypt
    ))
{
    templates2events("$_", qw(
    http-proxy-update
    bootstrap-console-save
}