#! /usr/bin/perl -w

# Need some thought on when the templates should be expanded and when the action should be called.

use esmith::Build::CreateLinks qw(:all);
my $event = "ipsec-update";

# ipsec-update

foreach (qw(
       /etc/letsencrypt/domains.txt
    ))
{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    ));
}


